### ISSUE TITLE
Remove native-TLS peer dependency

### ISSUE THREAD

**Issue by yoshuawuyts** [dbcfd/tls-async#1]
## Description
Having peer-dependencies can be tricky in Rust. If used versions don't line up, things don't compile, and people usually get rather cryptic error messages. Currently this crate has one peer dependency:

```toml
[dependencies]
native-tls = "0.2"
tls-async = "0.3.0-alpha.1"
```

It'd be great if we could change this to only require:

```toml
[dependencies]
tls-async = "0.3.0-alpha.1"
```

## Possible Implementation
In [lib.rs](https://github.com/dbcfd/tls-async/blob/master/src/lib.rs) native-tls could be re-exported:

```rust
pub use native_tls;
```

## Other Considerations
Ideally people would never need to interface with native-tls directly, having tls-async expose the right builders and wrappers. But that's a larger scope than what's outlined here, and warrants its own issues.

---
Thanks for reading!
